/**
 * Every standalone Angular component, grouped by portal — Mastande handoff.
 *
 *   node design-handoff/tools/components.mjs          # JSON
 *   node design-handoff/tools/components.mjs --md     # markdown
 *
 * The one-line description is taken from the component's own doc comment where
 * it has one — this codebase comments heavily and those sentences are better
 * than anything inferred from a class name. Where there is none, the file says
 * so rather than being given an invented description.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const APP = 'frontend/src/app';
const walk = (dir) =>
  readdirSync(dir).flatMap((e) => {
    const p = join(dir, e);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });

const rows = [];
for (const file of walk(APP)) {
  if (!file.endsWith('.ts') || file.endsWith('.spec.ts')) continue;
  const src = readFileSync(file, 'utf8');
  if (!/@Component\s*\(/.test(src)) continue;

  const selector = (src.match(/selector\s*:\s*['"`]([^'"`]+)['"`]/) ?? [])[1] ?? '(none)';
  const cls = (src.match(/export class (\w+)/) ?? [])[1] ?? '(anonymous)';
  const standalone = !/standalone\s*:\s*false/.test(src);

  /**
   * The first sentence of the JSDoc immediately above @Component.
   *
   * Taken from the block that ENDS closest above the decorator, not the first
   * block in the file — these files open with a long header comment about the
   * module, and using that would describe the wrong thing for every component.
   */
  const at = src.search(/@Component\s*\(/);
  const before = src.slice(0, at);
  const lastDoc = [...before.matchAll(/\/\*\*([\s\S]*?)\*\//g)].pop();
  let summary = null;
  if (lastDoc && before.slice(lastDoc.index + lastDoc[0].length).trim().length < 120) {
    summary = lastDoc[1]
      .split('\n').map((l) => l.replace(/^\s*\*ic?\s?/, '').replace(/^\s*\*\s?/, '').trim())
      .filter(Boolean).join(' ')
      .split(/(?<=[.!?])\s/)[0]
      .replace(/\s+/g, ' ')
      .trim();
    if (summary && summary.length > 200) summary = summary.slice(0, 197) + '…';
  }

  const rel = relative(APP, file);
  const portal =
    rel.startsWith('features/admin') ? 'Admin'
    : rel.startsWith('features/landlord') ? 'Landlord'
    : rel.startsWith('features/tenant') ? 'Tenant'
    : rel.startsWith('features/account') ? 'Account (both roles)'
    : rel.startsWith('features/auth') ? 'Auth'
    : rel.startsWith('shared/') ? 'Shared'
    : rel.startsWith('core/') ? 'Core'
    : 'Public';

  rows.push({ portal, selector, cls, file: 'frontend/src/app/' + rel, summary, standalone });
}

rows.sort((a, b) => a.portal.localeCompare(b.portal) || a.selector.localeCompare(b.selector));

if (process.argv.includes('--md')) {
  const order = ['Public', 'Auth', 'Tenant', 'Landlord', 'Account (both roles)', 'Admin', 'Shared', 'Core'];
  const groups = new Map(order.map((o) => [o, []]));
  for (const r of rows) (groups.get(r.portal) ?? groups.set(r.portal, []).get(r.portal)).push(r);
  console.log('<!-- generated by design-handoff/tools/components.mjs -->');
  for (const [g, list] of groups) {
    if (!list.length) continue;
    console.log(`\n## ${g} — ${list.length} component(s)\n`);
    console.log('| Selector | Class | Renders |');
    console.log('|---|---|---|');
    for (const r of list) {
      console.log(`| \`${r.selector}\` | ${r.cls} | ${r.summary ?? '_no doc comment — see `' + r.file + '`_'} |`);
    }
  }
  console.log(`\n_${rows.length} components; ${rows.filter((r) => !r.standalone).length} not standalone._`);
} else {
  console.log(JSON.stringify({ total: rows.length, rows }, null, 2));
}
